### PR TITLE
Trying again to make double click work on mobile

### PR DESCRIPTION
**Pull request by kepatinin**
One more try...

### CODE REVIEW

**Comment by artsdatabank** [comment]
Test den: https://okologiskegrunnkart.test.artsdatabanken.no/pr/412

**Comment by artsdatabank** [comment]
Test den: https://okologiskegrunnkart.test.artsdatabanken.no/pr/412

**Review by bjornreppen — APPROVED** [review]
Nice!

**Comment by artsdatabank** [comment]
Test den: https://okologiskegrunnkart.test.artsdatabanken.no/pr/412

**Comment by artsdatabank** [comment]
Test den: https://okologiskegrunnkart.test.artsdatabanken.no/pr/412

**Comment by artsdatabank** [comment]
Test den: https://okologiskegrunnkart.test.artsdatabanken.no/pr/412

**Pull request merged**
