### PR TITLE
Update visible layers from url

### PR DESCRIPTION
**Pull request by kepatinin**
Update layers and favorites from URL
Seems that the PR build is still not working...

### CODE REVIEW

**Comment by artsdatabank** [comment]
Test den: https://okologiskegrunnkart.test.artsdatabanken.no/pr/418

**Comment by artsdatabank** [comment]
Test den: https://okologiskegrunnkart.test.artsdatabanken.no/pr/418

**Review by bjornreppen — APPROVED** [review]
Good job! One issue, by loading

**Comment by kepatinin** [comment]
Well spotted!!! I will fix it, forgot the case when we don't have lat/lng or layers... I will fix it

**Comment by artsdatabank** [comment]
Test den: https://okologiskegrunnkart.test.artsdatabanken.no/pr/418

**Pull request merged**
